"""
Command Department Specialists (X001–X010)
Responsible for the core orchestration, planning, routing, decomposition,
context management, progress control, and final response synthesis.
"""
from typing import List
from .models import Specialist

COMMAND_SPECIALISTS: List[Specialist] = [
    Specialist(
        id="X001",
        name="Supreme Commander",
        department="Command",
        role="Master Orchestrator & Task Coordinator",
        description="Coordinates end-to-end task execution, assesses complexity, determines multi-department allocation, and manages escalation or retry triggers.",
        capabilities=["orchestration", "complexity-assessment", "department-allocation", "escalation", "supervision"],
        relevant_tools=["get_system_info", "list_skills"],
        input_requirements=["user_request", "conversation_history"],
        expected_output="High-level orchestration directive and execution governance.",
        is_core=True,
        required_permissions=["system_read"],
        prompt_guidelines="Lead task execution with high strategic awareness. Decide fast vs deep execution path and ensure seamless coordination across all departments."
    ),
    Specialist(
        id="X002",
        name="Intent Detector",
        department="Command",
        role="User Intent & Goal Extraction Specialist",
        description="Analyzes user utterances to accurately classify primary goals, implicit requirements, question types, and operational mode (conversational, analytical, or automated).",
        capabilities=["intent-classification", "goal-extraction", "mode-detection", "semantic-parsing"],
        relevant_tools=[],
        input_requirements=["user_message"],
        expected_output="Structured user intent, goals, and mode classification.",
        is_core=True,
        required_permissions=[],
        prompt_guidelines="Dissect user statements to extract true intent, underlying goals, and explicit/implicit constraints without guesswork."
    ),
    Specialist(
        id="X003",
        name="Requirement Analyst",
        department="Command",
        role="Requirements, Constraints & Scope Analyst",
        description="Extracts concrete technical requirements, target files, tech stacks, format specifications, and success criteria from requests.",
        capabilities=["requirements-gathering", "constraint-extraction", "scope-definition", "acceptance-criteria"],
        relevant_tools=["list_directory", "search_files"],
        input_requirements=["user_message", "detected_intent"],
        expected_output="Explicit list of requirements, boundaries, target files, and success criteria.",
        is_core=True,
        dependencies=["X002"],
        required_permissions=["filesystem_read"],
        prompt_guidelines="Identify all functional requirements, architectural constraints, target files, and verification standards."
    ),
    Specialist(
        id="X004",
        name="Master Planner",
        department="Command",
        role="Strategic Execution & DAG Planner",
        description="Constructs dependency-aware execution plans, ordering tasks sequentially or in parallel, while minimizing unnecessary specialist invocations.",
        capabilities=["execution-planning", "dag-generation", "dependency-resolution", "parallel-scheduling"],
        relevant_tools=[],
        input_requirements=["requirements", "intent", "available_specialists"],
        expected_output="Dependency graph (DAG) of subtasks assigned to target specialists.",
        is_core=True,
        dependencies=["X001", "X003"],
        required_permissions=[],
        prompt_guidelines="Design lean, efficient execution graphs with clear subtask dependencies and minimal token/step overhead."
    ),
    Specialist(
        id="X005",
        name="Department Router",
        department="Command",
        role="Multi-Department Allocator & Dispatcher",
        description="Evaluates required capabilities across all 10 departments and determines which departments must be activated for the task.",
        capabilities=["department-routing", "capability-matching", "cross-department-triage"],
        relevant_tools=[],
        input_requirements=["requirements", "intent"],
        expected_output="List of activated departments with relevance weights.",
        is_core=True,
        dependencies=["X003"],
        required_permissions=[],
        prompt_guidelines="Select the minimum necessary departments (e.g. Coding + Research for a research-backed script) without over-activating."
    ),
    Specialist(
        id="X006",
        name="Specialist Router",
        department="Command",
        role="Fine-Grained Specialist Selector",
        description="Selects the precise specialists within active departments based on capability scores, available tools, dependencies, and risk profile.",
        capabilities=["specialist-selection", "capability-scoring", "tool-matching", "workload-optimization"],
        relevant_tools=[],
        input_requirements=["activated_departments", "requirements"],
        expected_output="Selected specialist IDs mapped to execution steps.",
        is_core=True,
        dependencies=["X005"],
        required_permissions=[],
        prompt_guidelines="Match the most capable specialists to specific subtasks based on skill tags, tool needs, and verified capabilities."
    ),
    Specialist(
        id="X007",
        name="Task Decomposer",
        department="Command",
        role="Subtask Breakdown & Contract Specialist",
        description="Decomposes complex requests into atomic, verifiable subtasks with distinct input parameters and expected output contracts.",
        capabilities=["task-decomposition", "contract-definition", "granularity-tuning"],
        relevant_tools=[],
        input_requirements=["master_plan", "selected_specialists"],
        expected_output="Structured list of atomic subtasks with inputs and contracts.",
        is_core=True,
        dependencies=["X004", "X006"],
        required_permissions=[],
        prompt_guidelines="Break complex operations into atomic, self-contained subtasks with well-defined contracts."
    ),
    Specialist(
        id="X008",
        name="Context Manager",
        department="Command",
        role="Scoped Context & Artifact Bridge",
        description="Maintains shared state, filters irrelevant context to avoid token bloat, and passes structured artifacts between specialists.",
        capabilities=["context-scoping", "artifact-management", "token-optimization", "state-tracking"],
        relevant_tools=[],
        input_requirements=["task_context", "subtask_inputs"],
        expected_output="Clean, scoped context slices tailored for each executing specialist.",
        is_core=True,
        required_permissions=[],
        prompt_guidelines="Provide each specialist only the context and artifacts strictly necessary for its subtask."
    ),
    Specialist(
        id="X009",
        name="Progress Controller",
        department="Command",
        role="Execution Monitor, Retry & Loop Prevention",
        description="Monitors live subtask status, detects circular execution loops, manages retry counters, and triggers recovery strategies.",
        capabilities=["progress-monitoring", "loop-detection", "retry-management", "circuit-breaking"],
        relevant_tools=[],
        input_requirements=["execution_state", "subtask_results"],
        expected_output="Execution status updates, loop prevention signals, or recovery directives.",
        is_core=True,
        required_permissions=[],
        prompt_guidelines="Enforce strict loop prevention limits and ensure smooth execution flow with graceful failure recovery."
    ),
    Specialist(
        id="X010",
        name="Final Synthesizer",
        department="Command",
        role="Unified Response & Output Assembler",
        description="Combines outputs from all specialists into a coherent, high-quality, formatted user response with executive clarity.",
        capabilities=["response-synthesis", "formatting", "markdown-polishing", "executive-summary"],
        relevant_tools=[],
        input_requirements=["all_specialist_results", "quality_verdict"],
        expected_output="Polished final user response formatted in clean Markdown.",
        is_core=True,
        dependencies=["X009"],
        required_permissions=[],
        prompt_guidelines="Synthesize all specialist findings and artifacts into an articulate, well-structured, user-friendly response."
    ),
]
