FROM python:3.10-slim

WORKDIR /app
COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt && playwright install --with-deps chromium
COPY backend ./backend

EXPOSE 8000
WORKDIR /app/backend
CMD ["uvicorn", "api.server:app", "--host", "0.0.0.0", "--port", "8000"]
