import * as THREE from "three";
import type { GestureDefinition, GestureType } from "./types";

export class GestureLibrary {
  private static readonly gestures: Map<GestureType, GestureDefinition> = new Map([
    [
      "talk",
      {
        name: "talk",
        duration: 2.8,
        prepDuration: 0.45,
        holdDuration: 1.8,
        returnDuration: 0.55,
        cooldownDuration: 1.2,
        priority: 2,
        rightArmTarget: new THREE.Vector3(0.18, 0.95, 0.28),
        rightArmPole: new THREE.Vector3(0.38, 0.90, -0.15),
        rightHandRotation: new THREE.Euler(0.2, -0.3, 0.1),
        emotionalEnergy: 0.4,
      },
    ],
    [
      "explain",
      {
        name: "explain",
        duration: 3.4,
        prepDuration: 0.55,
        holdDuration: 2.1,
        returnDuration: 0.75,
        cooldownDuration: 2.0,
        priority: 3,
        rightArmTarget: new THREE.Vector3(0.24, 1.02, 0.35),
        rightArmPole: new THREE.Vector3(0.42, 0.92, -0.10),
        leftArmTarget: new THREE.Vector3(-0.20, 0.88, 0.22),
        leftArmPole: new THREE.Vector3(-0.38, 0.85, -0.15),
        rightHandRotation: new THREE.Euler(0.3, -0.4, 0.2),
        leftHandRotation: new THREE.Euler(0.2, 0.3, -0.1),
        torsoOffset: new THREE.Euler(0.04, 0.0, 0.0),
        emotionalEnergy: 0.5,
      },
    ],
    [
      "greeting",
      {
        name: "greeting",
        duration: 2.6,
        prepDuration: 0.4,
        holdDuration: 1.6,
        returnDuration: 0.6,
        cooldownDuration: 3.0,
        priority: 5,
        rightArmTarget: new THREE.Vector3(0.22, 1.30, 0.25),
        rightArmPole: new THREE.Vector3(0.40, 1.15, -0.10),
        rightHandRotation: new THREE.Euler(0.0, -0.2, 0.3),
        headOffset: new THREE.Euler(0.04, -0.05, 0.06),
        emotionalEnergy: 0.6,
      },
    ],
    [
      "point",
      {
        name: "point",
        duration: 2.8,
        prepDuration: 0.45,
        holdDuration: 1.7,
        returnDuration: 0.65,
        cooldownDuration: 2.5,
        priority: 4,
        rightArmTarget: new THREE.Vector3(0.15, 1.05, 0.45),
        rightArmPole: new THREE.Vector3(0.35, 1.00, -0.10),
        rightHandRotation: new THREE.Euler(0.4, -0.2, 0.1),
        headOffset: new THREE.Euler(0.02, 0.08, -0.03),
        emotionalEnergy: 0.5,
      },
    ],
    [
      "shrug",
      {
        name: "shrug",
        duration: 2.4,
        prepDuration: 0.4,
        holdDuration: 1.4,
        returnDuration: 0.6,
        cooldownDuration: 3.5,
        priority: 4,
        leftArmTarget: new THREE.Vector3(-0.25, 0.90, 0.20),
        leftArmPole: new THREE.Vector3(-0.42, 0.85, -0.15),
        rightArmTarget: new THREE.Vector3(0.25, 0.90, 0.20),
        rightArmPole: new THREE.Vector3(0.42, 0.85, -0.15),
        leftShoulderOffset: new THREE.Euler(0, 0, 0.08),
        rightShoulderOffset: new THREE.Euler(0, 0, -0.08),
        headOffset: new THREE.Euler(0.0, 0.0, 0.08),
        emotionalEnergy: 0.5,
      },
    ],
    [
      "thinking",
      {
        name: "thinking",
        duration: 3.8,
        prepDuration: 0.6,
        holdDuration: 2.5,
        returnDuration: 0.7,
        cooldownDuration: 2.5,
        priority: 4,
        rightArmTarget: new THREE.Vector3(0.12, 1.25, 0.22),
        rightArmPole: new THREE.Vector3(0.32, 0.95, -0.10),
        rightHandRotation: new THREE.Euler(0.5, -0.4, 0.2),
        headOffset: new THREE.Euler(-0.08, -0.12, 0.06),
        emotionalEnergy: 0.3,
      },
    ],
    [
      "excited",
      {
        name: "excited",
        duration: 2.5,
        prepDuration: 0.35,
        holdDuration: 1.6,
        returnDuration: 0.55,
        cooldownDuration: 3.0,
        priority: 4,
        leftArmTarget: new THREE.Vector3(-0.24, 1.15, 0.28),
        leftArmPole: new THREE.Vector3(-0.45, 1.05, -0.10),
        rightArmTarget: new THREE.Vector3(0.24, 1.15, 0.28),
        rightArmPole: new THREE.Vector3(0.45, 1.05, -0.10),
        headOffset: new THREE.Euler(0.06, 0.0, 0.0),
        emotionalEnergy: 0.85,
      },
    ],
    [
      "agree_nod",
      {
        name: "agree_nod",
        duration: 1.8,
        prepDuration: 0.3,
        holdDuration: 1.1,
        returnDuration: 0.4,
        cooldownDuration: 2.0,
        priority: 3,
        headOffset: new THREE.Euler(0.12, 0.0, 0.0),
        emotionalEnergy: 0.4,
      },
    ],
    [
      "disagree_shake",
      {
        name: "disagree_shake",
        duration: 1.8,
        prepDuration: 0.3,
        holdDuration: 1.1,
        returnDuration: 0.4,
        cooldownDuration: 2.5,
        priority: 3,
        headOffset: new THREE.Euler(0.0, 0.16, 0.0),
        emotionalEnergy: 0.4,
      },
    ],
    [
      "confused",
      {
        name: "confused",
        duration: 2.6,
        prepDuration: 0.4,
        holdDuration: 1.6,
        returnDuration: 0.6,
        cooldownDuration: 3.0,
        priority: 3,
        headOffset: new THREE.Euler(-0.04, 0.08, 0.12),
        rightShoulderOffset: new THREE.Euler(0, 0, -0.05),
        emotionalEnergy: 0.35,
      },
    ],
    [
      "idle",
      {
        name: "idle",
        duration: 1.0,
        prepDuration: 0.2,
        holdDuration: 0.6,
        returnDuration: 0.2,
        cooldownDuration: 0.0,
        priority: 0,
        emotionalEnergy: 0.2,
      },
    ],
  ]);

  public static get(type: GestureType): GestureDefinition {
    return this.gestures.get(type) ?? this.gestures.get("idle")!;
  }
}
